job/urls.py
from django.urls import path, include
from job.views import *

app_name = 'job'

urlpatterns = [
    path('test/', test, name='test')
]

learning/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import chat.urls
import medical.urls
import portal_auth.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('medical/', include(medical.urls)),
    path('chat/', include(chat.urls)),
    path('portal_auth/', include(portal_auth.urls)),
]

urlpatterns += static(settings.UPLOADS_URL, document_root=settings.UPLOADS_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from portal_auth import views as portal_auth_views

app_name = 'portal_auth'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name="portal_auth/login_form.html"), name='login'),
    path('login/email', portal_auth_views.login_email, name='login-email'),
    path('login/email/send_code/<str:email>', portal_auth_views.send_code, name='login-email-send-code'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/base.html
{% load static menu_tag bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    </title>
    <link rel="stylesheet" type="text/css" href="{% static "medical/css/base/base.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/widgets.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "medical/css/library/common.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "medical/css/components/menu.css" %}">
    {% bootstrap_css %}
    <script type="application/javascript" src="{% static "medical/js/base.js" %}"></script>
    {% bootstrap_javascript %}
    {% block medical_page_css %}
    {% endblock %}
    {% block medical_page_js %}
    {% endblock %}
    <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
<div id="container">
    <div id="header">
        <div id="branding">
            <h1 id="site-name"><a href="/medical/">医疗系统 Medical System</a></h1>
        </div>
        <div id="user-tools">
            {% if user.is_authenticated %}
                <p>Welcome, {{ user.username }}</p>
                <a href="{% url 'portal_auth:logout' %}">登出</a>
            {% else %}
                <a href="{% url 'portal_auth:login' %}">登录</a>
            {% endif %}
        </div>
    </div>
    <div id="header-menu" class="header-menu">
        {% menu_item_list %}
    </div>
    <div class="medical-main">
        <div class="medical-main-container fix">
            {% block content %}
                <section id="main">
                    Default content
                </section>
            {% endblock content %}
        </div>
    </div>
</div>
{% block inline_script %}
{% endblock %}
</body>
</html>

base/templates/base/dummy.html
{% extends template %}